engines:
  eslint:
    enabled: true
    checks:
      guard-for-in:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
ratings:
  paths:
  - "**.js"
exclude_paths:
- "handlebars.js"
- "test/**"